version: '3.8'
services:
  db:
    image: postgres:13
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmoteka
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./migrations_docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    hostname: app
    environment:
    # Set only if you want to choose spicific path
      CONFIG_PATH_DOCKER: configs/server_docker.toml
    ports:
      - "8081:8081"
