port = "8080"
db_type = "postgres"
db_path = "postgresql://postgres:Sassassa12@localhost:5432/filmoteka?sslmode=disable"
schema_path = "file:///migrations/20240608145718_create_tables.up.sql"
log_level = "debug"